title: Catalin Stan # your name (or website title) here
logo: "images/CSlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Description 
  <br>
  Experienced in requirement analysis, data modeling, and software design, with proficiency in Python, SQL, and Tableau.
  <br>
  Known for strong work ethic, teamwork, and effective time management. 
  <br>
  Certified in Business Analysis and CompTIA Data+, with hands-on project experience.
  <br>
  Seeking to apply skills to enhance client outcomes and efficiency.
  <br>
  Certifications 
  <br>
  CompTia Data+
  <br>
  BCS Business Analysis Foundation
  <br>
  Python for Data Analysis
  <br>
  Essential Statistics for Data Analysis
  <br><br>
  <a href="https://www.linkedin.com/in/catalin-stan-42190276/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
